---
- name: Python Based Things Installer
  hosts: all
  remote_user: ubuntu
  become: true
  become_user: root
  become_method: sudo
  pre_tasks:

    # Update apt cache and install python 2 with devel.

    - name: Update APT cache
      raw: apt-get update
      become: True
      changed_when: false

    - name: Install python
      apt: name=python

    - name: Install python-dev
      apt: name=python-dev

  roles:
    - common
