---
- name: ansible-pip
  include: get_url.ym
  command: "python get-pip.py"
  when: ansible_os_family == "Ubuntu"
  args:
    chdir: /tmp

- name: ansible-matplotlib
  command: python -mpip install -U matplotlib
  vars:
    python_path: '{{lookup("env","PYTHON_PATH") | default("false")}}'

