galaxy_info:
 author: Armagan Karatosun
 description: Install Python Pip
 company: Equinix


 license: GPL2
 min_ansible_version: 1.2


 platforms:
   - name: Ubuntu
     versions:
     - all

 galaxy_tags:
    - system
    - python

dependencies: []
